server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: bank-client-service
          uri: lb://bank-client-service
          predicates:
            - path=/clients/**
        - id: bank-product-service
          uri: lb://bank-product-service
          predicates:
            - path=/products/**
        - id: bank-account-service
          uri: lb://bank-account-service
          predicates:
            - path=/accounts/**
        - id: bank-credit-service
          uri: lb://bank-credit-service
          predicates:
            - path=/credits/**
        - id: bank-transaction-account-service
          uri: lb://bank-transaction-account-service
          predicates:
            - path=/transactions/accounts/**
        - id: bank-transaction-credit-service
          uri: lb://bank-transaction-credit-service
          predicates:
            - path=/bank-transactions/credits/**
