server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/masnoviembre/bootcamp-21
          search-paths: Project01/bank-config-data
  application:
    name: bank-config-service

